# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: Calculator with CI

on:
  push:
    branches:
      - 'feat*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
